[package]
name = "image-grayscaler"
authors = ["Antonio Masotti <toniomasotti@gmail.com>"]
keywords = ["image", "grayscale"]
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
image = "0.25.1"
log = "0.4.21"
