[package]
name = "eda-polars"
version = "0.1.0"
edition = "2021"

[dependencies]
blas-src = "0.10.0"
chrono = "0.4.38"
either = "1.12.0"
evcxr = "0.17.0"
ndarray = "0.15.6"
ndarray-linalg = "0.16.0"
ndarray-rand = "0.14.0"
plotters = "0.3.6"
polars = "0.40.0"
smartcore = "0.3.2"
statrs = "0.17.1"
